version: '3.3'

services:
  nextjs:
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
